# Generated by Django 2.1.5 on 2019-01-24 13:04

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pokemon_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Pokemon')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Pokemon')),
            ],
        ),
    ]
